server:
  port: ${SERVICE_PORT:8888}
spring:
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/shared
  profiles:
    active: composite
  security:
    user:
      password: ${CONFIG_PASSWORD:nimadirxavfsizlik}
