services:
  hosts:
    post: http://localhost:8081
    gateway: http://localhost:8080
    user: http://localhost:8082
    follow: http//localhost:8083
  ports:
    post: 8081
    gateway: 8080
    user: 8082
    follow: 8083