services:
  hosts:
    post: http://localhost:8081
    gateway: http://localhost:8080
    user: http://localhost:8082
    follow: http://localhost:8083
    file: http://localhost:8084
    auth: http://localhost:8085
  ports:
    post: 8081
    gateway: 8080
    user: 8082
    follow: 8083
    file: 8084
    auth: 8085

spring:
  security:
    oauth2:
      resourceserver:
        user-info-uri: ${services.hosts.auth}/internal/user-info
        jwt:
          issuer-uri: http://localhost:8085