server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # USER SERVICE
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        # POST SERVICE
        - id: post-service
          uri: http://localhost:8081
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1

        # FOLLOW SERVICE
        - id: follow-service
          uri: http://localhost:8083
          predicates:
            - Path=/follow/**
          filters:
            - StripPrefix=1