server:
  port: ${services.ports.post}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thread_post_db
    username: postgres
    password: 1012
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: post
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  sql:
    init:
      mode: never